version: '3.7'

services:

  composer:
    image: composer:2
    container_name: ${APP_PROJECT_NAME}-composer
    volumes:
      - .:/var/www/html
      - ${HOME}/.cache:/tmp/cache
    working_dir: /var/www/html
    networks:
      - app

  yarn:
    image: node:latest
    container_name: ${APP_PROJECT_NAME}-yarn
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['yarn']
    networks:
      - app
